:wrench: (setup) : Config Strapi
vivianeglz/webians-v1 pull request #37
Opened 2021-12-22 13:21 UTC by JenniferMrm

2022-01-03 09:15 UTC, vivianeglz requested changes

2022-01-03 09:15 UTC, vivianeglz commented on api/src/admin/app.example.js
> +      // 'vi',
On a besoin de tout garder en commentaire ?

2022-01-03 09:15 UTC, vivianeglz commented on api/public/robots.txt
> +# Disallow: /
Il ne faudra pas oublier de décommenter

2022-01-03 09:15 UTC, vivianeglz commented on api/config/admin.js
> +    secret: env("ADMIN_JWT_SECRET", "096409ba09765d6d891529c75937c6c8")
Il vaut mieux utiliser un fichier de config je pense

2022-01-03 09:15 UTC, vivianeglz commented on api/config/database.js
> +      ssl: env.bool("DATABASE_SSL", false)
Pareil ce serait mieux avec un fichier de config je pense

2022-01-03 10:15 UTC, antoinechassagne commented on api/src/admin/app.example.js
> +      // 'vi',
Effectivement, c'est un fichier généré par Strapi, je pense qu'on peut le nettoyer 👍

2022-01-03 10:16 UTC, antoinechassagne commented on api/public/robots.txt
> +# Disallow: /
Yes, on pourrait rajouter un commentaire : `# @TODO` pour ne pas oublier

2022-01-03 10:24 UTC, antoinechassagne commented on api/config/admin.js
> +    secret: env("ADMIN_JWT_SECRET", "096409ba09765d6d891529c75937c6c8")
En fait c'est une bien meilleure pratique d'utiliser des variables d'environnement, c'est d'ailleurs comme ça que fonctionnent la plupart des providers. En terme de DX, ça change rien car tu as accès un fichier `.env` qui n'est pas versionné et où tu listes les variables et leurs valeurs. Ce fichier est lu et toutes les variables sont injectées dans le process Node. Tu trouveras un fichier `.env.example` avec toutes les variables que tu dois remplir

2022-01-03 10:28 UTC, antoinechassagne commented on api/config/admin.js
> +    secret: env("ADMIN_JWT_SECRET", "096409ba09765d6d891529c75937c6c8")
C'est d'ailleurs ce que recommande le document 12 Factors App : https://12factor.net/fr/config

2022-01-10 15:56 UTC, HubM commented on api/config/database.js
> +      ssl: env.bool("DATABASE_SSL", false)
yes d'accord avec toi Viviane, le `.env` contiendra ces valeurs

2022-01-10 18:17 UTC, antoinechassagne commented on api/config/database.js
> +      ssl: env.bool("DATABASE_SSL", false)
Ah mais je viens de comprendre pourquoi vous dites ça 😂 
En fait, la fonction `env()` va chercher dans le .env la variable et si elle ne la trouve pas, elle regarde le deuxième paramètre qui est un fallback. En gros ça se lit comme ça `env("NOM DE LA VARIABLE A CHECKER DANS LE .ENV" , "valeur fallback si on trouve pas la variable dans .env")`
Donc avec Jennifer on a rempli des fallbacks par défaut, mais évidemment il faudra remplir le fichier .env.

2022-01-11 10:32 UTC, vivianeglz approved these changes
👍

2022-01-11 10:33 UTC, merged