✨ (design-system ): add cta primary
vivianeglz/webians-v1 pull request #42
Opened 2022-01-10 09:41 UTC by HubM

2022-01-10 09:50 UTC, JenniferMrm approved these changes
:+1:

2022-01-12 13:22 UTC, vivianeglz requested changes

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-primary/cta-primary.test.js
> +    expect(wrapper.classes()).toContain("cta-primary--m");
Je pense que tu n'as pas forcément besoin de tester la classe `cta-primary-m` la classe de base suffit

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-primary/cta-primary.test.js
> +    expect(wrapper.props().size).toBe("s");
Du coup là il faudrait tester si le composant monté est un lien et si la classe est bien `cta-primary--s`

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-tertiary/cta-tertiary.test.js
> +    expect(wrapper.classes()).toContain("cta-tertiary--m--icon-left");
Pareil

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-secondary/cta-secondary.test.js
> +});
Il faudrait le compléter avec les tests comme sur le primary

2022-01-12 13:22 UTC, vivianeglz commented on ui/helpers/_functions/tests/wait.js
> +export default ms => new Promise(resolve => setTimeout(resolve, ms));
Normalement le fichier existe déjà dans les commons

2022-01-12 13:22 UTC, vivianeglz commented on ui/helpers/_functions/tests/fragment_wrapper.js
> +};
A bouger dans les common du coup

2022-01-12 13:22 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +  }
Ca ne doit pas être une variation spécifique mais appartenir au style par défaut

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-tertiary/cta-tertiary.test.js
> +    expect(wrapper.props().iconDirection).toBe("icon-left");
Same

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-tertiary/cta-tertiary.test.js
> +    expect(wrapper.props().iconDirection).toBe("icon-right");
Same

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-tertiary/index.vue
> +    },
Il ne faut pas lui passer une prop state mais une prop disabled qui sera un boolean à false par défaut et qui s'appliquera directement dans le render sur les attributs

2022-01-12 13:22 UTC, vivianeglz commented on ui/components/globals/cta/cta-tertiary/index.vue
> +      }
Pour moi il n'y a pas besoin de gérer l'emplacement, cela se fera directement dans le slot `<icon><p>...</p>` ou `<p>...</p><icon/>`

2022-01-12 13:22 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +      }
Pas besoin de mettre une position absolute, il faut juste faire un flex sur le container et ajouter un margin sur le .icon

2022-01-12 13:22 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +      }
Same

2022-01-12 13:22 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +        top: -0.375rem;
Same

2022-01-12 13:22 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +        top: -0.375rem;
Same

2022-01-12 13:22 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +  }
Il faudrait se baser sur son état `:disabled` et non une classe

2022-01-14 08:58 UTC, vivianeglz approved these changes
👍

2022-01-14 08:59 UTC, merged